Enroll no-240840116065

Practical - 03

AIM: Apply ƒltering, sorting, aggregation, and GroupBy operations on real-world datasets.

Step1: Display the Dataset

In [ ]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

Step 2: Create the Dataset

In [ ]:
# Create a dictionary containing structured employee details
data = {
     "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Neha", "Vivek", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "City": ["Surat", "Navsari", "Surat", "Valsad", "Surat", "Navsari", "Valsad", "Surat"],
     "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience": [2, 1, 5, 4, 2, 6, 8, 3]
}

Step 3: Create DataFrame

In [ ]:
# Convert the dictionary into a tabular Pandas DataFrame structure
df = pd.DataFrame(data)

# Print the final DataFrame to the console to view the table
print(df)

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

Step 4: Filter Data

Display Employees From IT Department

In [ ]:
# Filter and display only the employees who work in the IT department
df[df["Department"] == "IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Display Employees with Salary Greater Than 50,000

In [ ]:
#Display the Employees whose salary is greater than 50,000
df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Display Employee From Surat

In [ ]:
#Display the Employees who are from "Surat"
df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Apply Multiple Conditions

In [ ]:
#Display the Employees whose Department is "IT" and Salary is greater than 50,000
df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Step 5: Sort Data

Sort Salary in Ascending Order

In [ ]:
# Sort rows based on the 'Salary' column (defaults to ascending order)
df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Sort Salary in Descending Order

In [ ]:
# Sort rows by 'Salary' and set ascending to False for a descending order result
df.sort_values(by="Salary", ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

Sort by Department and Salary

In [ ]:
# Sort rows using a list of columns and map corresponding boolean flags for sort order
df.sort_values(by=["Department", "Salary"], ascending=[True, False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

Step 6: Perform Aggregation


Calculate Total Salary

In [ ]:
# Calculate the total sum of the Salary column
df["Salary"].sum()

np.int64(376000)

Calculate Average Salary

In [ ]:
#Calculate the average salary of all employees
df["Salary"].mean()

np.float64(47000.0)

Find Highest Salary

In [ ]:
#Find the Highest salary from the Salary column
df["Salary"].max()

60000

Find Lowest Salary

In [ ]:
# Find the lowest value in the Salary column
df["Salary"].min()

38000

Count Employees

In [ ]:
#Count the number of non-empty values in the Emp_ID column
df["Emp_ID"].count()

np.int64(8)

Step7: Perform GroupBy Operations

Average Salary Department-wise

In [ ]:
#Calculate the Average Salary for each Department
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Minimum Salary Department-wise

In [ ]:
#Calculate the Minimum Salary for each Department
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Count Total Employees Department-wise

In [ ]:
# Group data by the 'Department' column and compute the count of non-null 'Emp_ID' values per group
df.groupby("Department")["Emp_ID"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

Group by City

In [ ]:
#Group the data by "City" and Calculate the Average Salary for each City
df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

Total Salary Deparetment-wise

In [ ]:
# Total salary sum for each department
df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Step 8: Multiple Aggregation Functions

In [ ]:
#Group the data by "Department" and Calculate multiple statistics for the Salary column
df.groupby("Department")["Salary"].agg(["count","sum","mean","min","max"])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

Step 9: Save the Result

In [ ]:
#Save the DataFrame as a CSV file named "Employee_Data.csv" and index=False prevents pandas from saving the row index as an extra column after that print success message
df.to_csv("Employee_Data.csv",index=False)
print("Dataset Saved Successfully.")

Dataset Saved Successfully.

Download CSV file

In [ ]:
#Save employee data as a CSV file
df.to_csv("Employee_Data.csv",index=False)
#Import files module to download the file
from google.colab import files
#Download the CSV file
files.download("Employee_Data.csv")