Enrollment NO- 240840116065

Practical-01

AIM- Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON les using Pandas.

Step 1: Import Pandas Library

In [ ]:
# Step 1: Import the pandas library
import pandas as pd

Step 2: Create Sample Data

In [ ]:
# Step 2: Create sample student data
data={
    "ID":[101,102,103,104,105,106,107],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Krisha","Harry"],
    "Age":[20,21,19,20,22,24,28],
    "City":["Surat","Navsari","Valsad","Bharuch","Surat","Gandhinagar","Ahmedabad"],
    "Marks":[85,92,78,88,81,84,90]
}

Step 3: Create a DataFrame

In [ ]:
# Step 3: Create a DataFrame from the sample data
df=pd.DataFrame(data)

# Display the DataFrame
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 4: Save Data as CSV File

In [ ]:
# Step 4: Save the DataFrame as a CSV file
df.to_csv("students.csv",index=False)

# Display success message
print("csv file created successfully.")

csv file created successfully.

Step 5: Save Data as Excel File

In [ ]:
# Step 5: Save the DataFrame as an Excel file
df.to_excel("students.xlsx", index=False)

# Display success message
print("Excel file created successfully.")

Excel file created successfully.

Step 6: Save Data as JSON File

In [ ]:
# Step 6: Save the DataFrame as a JSON file
df.to_json("students.json", orient="records", indent=4)


# Display success message
print("JSON File created successfully.")

JSON File created successfully.

Step 7: Read the CSV File

In [ ]:
# Step 7: Read the CSV file
df_csv=pd.read_csv("students.csv")

# Display the CSV data
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 8: Read the Excel File

In [ ]:
# Step 8: Read the Excel file
df_excel=pd.read_excel("students.xlsx")

# Display the Excel data
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 9: Read the JSON File

In [ ]:
# Step 9: Read the JSON file
df_json=pd.read_json("students.json")

# Display the JSON data
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 10: Display First Five Records

In [ ]:
# Step 10: Display the first five records
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

Step 11: Display Last Five Records

In [ ]:
# Step 11: Display the last five records
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 12: Display Dataset Information

In [ ]:
# Step 12: Display information about the dataset
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

13.Display the statistical summary

In [ ]:
# Step 13: Display the statistical summary of numerical columns
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

14.Display Dataset Shape

In [ ]:
# Step 14: Display the shape of the dataset
# Output shows: (number of rows, number of columns)
df_csv.shape

(7, 5)

15.Display column names

In [ ]:
# Step 15: Display all column names
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

16.Display Data Types

In [ ]:
# Step 16: Display the data type of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

17.Check for Missing Values

In [ ]:
# Step 17: Check for missing values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

18.Display a Single Column

In [ ]:
# Step 18: Display only the marks column
df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

19.Display Multiple Columns

In [ ]:
# Step 19: Display multiple columns
df_csv[["Name","Marks"]]

     Name  Marks
0   Rahul     85
1   Priya     92
2    Amit     78
3    Riya     88
4   Karan     81
5  Krisha     84
6   Harry     90

20.Filter Records

In [ ]:
# Step 20: Display students who scored more than 85 marks
df_csv[df_csv["Marks"] >80 ]

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

21.Calculate the Average marks

In [ ]:
# Step 21: Calculate the average marks of all students
df_csv["Marks"].mean()

np.float64(85.42857142857143)

22.Sort Data

In [ ]:
# Step 22: Sort the data by marks in descending order
df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   28    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

23.Display Data Set

In [ ]:
# Step 23: Dispaly the Data Set
print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90